AQL CRUD Operations + OneShard DB Creation
arangodb/feed pull request #10
Opened 2023-07-20 17:46 UTC by hkernbach

2023-07-21 15:22 UTC, neunhoef requested changes

2023-07-21 15:22 UTC, neunhoef commented on pkg/operations/normal.go
> +					defer cursor.Close()
I fear this might not work as intended. Let me explain: `defer` statements will only be executed, when the **entire function** is left. Since we are creating cursors here in a loop, we have something we do not want: Either all cursors are closed at the end of the function (not desired), or even worse, all these defers are executed at the end, but they refer to the **local** variable cursor and only close the last one. I do not understand go well enough to understand which would happen, but I think either would be suboptimal. I suggest to just directly close the cursor in the `else` part, since it is no longer needed.

2023-07-21 15:22 UTC, neunhoef commented on pkg/operations/normal.go
> +					defer cursor.Close()
Same as above.

2023-07-21 15:22 UTC, neunhoef commented on pkg/operations/normal.go
> +				_, err = db.Query(ctx, query, bindVars)
We should ask somebody in the go team, if this is OK or if this prevents the cursor object from being closed. I do not know the consequences, but we should check with them.

2023-07-21 15:22 UTC, neunhoef commented on pkg/operations/normal.go
> +				_, err = db.Query(ctx, query, bindVars)
Same as above.

2023-07-21 15:22 UTC, neunhoef commented on pkg/operations/normal.go
> +						_, err = db.Query(ctx, query, bindVars)
Same as above.

2023-07-21 15:49 UTC, hkernbach commented on pkg/operations/normal.go
> +					defer cursor.Close()
Yes, I think you might be correct here. Let's change this on Monday.

2023-07-24 14:58 UTC, neunhoef approved these changes
LGTM

2023-07-24 14:59 UTC, merged